---
- name: "Deploy service [{{ service_name }}]"
  block:
    - name: "Deploy [{{ service_name }}] service"
      community.docker.docker_swarm_service:
        name: "{{ service_name }}"
        image: "{{ registry_name }}{{ service_name }}:{{ version }}"
        state: present
        force_update: true  # В случае, если проект имеет реальную версионность, а не все время latest, отключить force_update либо сделать проверку на latest
        networks:
          - name: "{{ network_name }}"
        publish:
          - mode: ingress
            protocol: tcp
            published_port: 3001
            target_port: 80
  # tags: "{{ service_name }}"
