---
- name: "Create secret [{{ service_name }}]"
  vars:
    env_file: "{{ lookup('template', '{{ service_name }}/.env.j2') }}"
  community.docker.docker_secret:
    name: "{{ service_name }}.env"
    data: "{{ env_file | b64encode }}"
    labels:
      secret: "{{ env_file | hash('sha1') }}"
    data_is_b64: true
    state: present

# - name: "-------Service [{{ service_name }}] Debug-------"
#   vars:
#     env_file: "{{ lookup('template', '{{ service_name }}/.env.j2') }}"
#   debug:
#     msg: "{{ env_file }}"
