---
- name: "Configure secrets for [{{ service_name }}]"
  block:
    - name: "Include task to create secret for [{{ service_name }}]"
      ansible.builtin.include_tasks: "create_secret.yml"
  # tags: "{{ service_name }}"

  rescue:
    - name: "Remove service [{{ service_name }}] if secret creation fails"
      community.docker.docker_swarm_service:
        name: "{{ service_name }}"
        state: absent

    - name: "Re-attempt to create secret for [{{ service_name }}]"
      ansible.builtin.include_tasks: "create_secret.yml"
