---
- name: "Configure config for [{{ service_name }}]"
  block:
    - name: "Include task to create config for [{{ service_name }}]"
      ansible.builtin.include_tasks: "create_config.yml"
  # tags: "{{ service_name }}"

  rescue:
    - name: "Remove service [{{ service_name }}] if config creation fails"
      community.docker.docker_swarm_service:
        name: "{{ service_name }}"
        state: absent

    - name: "Re-attempt to create config for [{{ service_name }}]"
      ansible.builtin.include_tasks: "create_config.yml"
