galaxy_info:
  author: Konstantin Kochervrin
  description: Updating servers and installing the Docker engine
  company: KK Company
  license: MIT
  min_ansible_version: "2.9"

dependencies:
  - role: preconfig
