---
- name: Preconfiguring servers
  when: ansible_facts['distribution'] == 'Ubuntu'
  block:
    - name: Update and upgrade all packages to the latest version
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        cache_valid_time: 86400

    - name: Add Universe repository
      ansible.builtin.apt_repository:
        repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
        state: present

    - name: Set timezone to Europe/Kyiv
      community.general.timezone:
        name: Europe/Kyiv
