---
- name: "Configure secrets for [{{ service_name }}]"
  ansible.builtin.include_tasks: "../manage_secrets.yml"

- name: "Deploy service [{{ service_name }}]"
  block:
    - name: "Deploy [{{ service_name }}] service"
      community.docker.docker_swarm_service:
        name: "{{ service_name }}"
        image: "{{ registry_name }}{{ service_name }}:{{ version }}"
        state: present
        force_update: true  # В случае, если проект имеет реальную версионность, а не все время latest, отключить force_update либо сделать проверку на latest
        networks:
          - name: "{{ network_name }}"
        publish:
          - mode: ingress
            protocol: tcp
            published_port: 3002
            target_port: 3000
        secrets:
          - secret_name: "{{ service_name }}.env"  # Name of the secret to be used
            filename: "/opt/app/.env"  # Path where the secret will be mounted
  # tags: "{{ service_name }}"
